### PR TITLE
[FEATURE] Dark Mode Added Button

### PR DESCRIPTION
**Pull request by Horror26**
#  Added Dark Mode Button
Screenshot
image 2.

### CODE REVIEW

**Review by vish-rt — APPROVED** [review]
Looks good to me

**Review by vish-rt — CHANGES_REQUESTED** [review]
- [ ] Don't push the `.vscode` folder. It is a local dependency and does not need to be on production.
- [ ] Also recommend adding screenshots of dark mode webpage on `README.md`

**Review by vish-rt — APPROVED** [review]
Great!

**Review by demonkillerr — APPROVED** [review]
LGTM!

**Pull request merged**
